services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "433:433"
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: always
    env_file:
      - ./requirements/.env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file:
      - ./requirements/.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /Users/rkoper/data/mariadb
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /Users/rkoper/data/wordpress

networks:
  inception:
